module.exports = [
  {
    id: "movie-1",
    title: "Get Out",
    subGenre: "Psychological Horror",
    releaseYear: 2017,
    director: "Jordan Peele",
    cast: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"],
    rating: 7.8,
    ratingSource: "IMDb",
    imdbUrl: "https://www.imdb.com/title/tt5052448/",
    review: "A brilliant social satire wrapped in a tense, deeply unsettling psychological thriller."
  },
  {
    id: "movie-2",
    title: "Obsession",
    subGenre: "Supernatural Horror",
    releaseYear: 2025,
    director: "Curry Barker",
    cast: ["Michael Johnston", "Inde Navarrette", "Cooper Tomlinson"],
    rating: 7.9,
    ratingSource: "IMDb",
    imdbUrl: "https://www.imdb.com/title/tt33423719/",
    review: "A dark, twisting supernatural horror film that turns romantic fixation into a sinister nightmare."
  },
  {
    id: "movie-3",
    title: "Hereditary",
    subGenre: "Supernatural Horror",
    releaseYear: 2018,
    director: "Ari Aster",
    cast: ["Toni Collette", "Alex Wolff", "Milly Shapiro"],
    rating: 7.3,
    ratingSource: "IMDb",
    imdbUrl: "https://www.imdb.com/title/tt7784604/",
    review: "A harrowing exploration of grief and ancestral tragedy delivered with unrelenting tension."
  },
  {
    id: "movie-4",
    title: "Smile",
    subGenre: "Psychological Horror",
    releaseYear: 2022,
    director: "Parker Finn",
    cast: ["Sosie Bacon", "Jessie T. Usher", "Kyle Gallner"],
    rating: 6.5,
    ratingSource: "IMDb",
    imdbUrl: "https://www.imdb.com/title/tt15474916/",
    review: "An effective horror film built on eerie visual cues, trauma metaphors, and jarring scares."
  },
  {
    id: "movie-5",
    title: "Smile 2",
    subGenre: "Psychological Horror",
    releaseYear: 2024,
    director: "Parker Finn",
    cast: ["Naomi Scott", "Rosemarie DeWitt", "Lukas Gage"],
    rating: 6.8,
    ratingSource: "IMDb",
    imdbUrl: "https://www.imdb.com/title/tt29268110/",
    review: "A disturbing, energetic sequel that amplifies the psychological terror inside a pop-star narrative."
  },
  {
    id: "movie-6",
    title: "Weapons",
    subGenre: "Supernatural Horror",
    releaseYear: 2026,
    director: "Zach Cregger",
    cast: ["Julia Garner", "Josh Brolin", "Alden Ehrenreich"],
    rating: 7.6,
    ratingSource: "IMDb",
    imdbUrl: "https://www.imdb.com/title/tt26443598/",
    review: "A sprawling, multi-perspective horror mystery that turns a chilling mass disappearance into a tense examination of grief and scapegoating."
  },
  {
    id: "movie-7",
    title: "Barbarian",
    subGenre: "Survival Horror",
    releaseYear: 2022,
    director: "Zach Cregger",
    cast: ["Georgina Campbell", "Bill Skarsgård", "Justin Long"],
    rating: 7.0,
    ratingSource: "IMDb",
    imdbUrl: "https://www.imdb.com/title/tt15791034/",
    review: "A wildly unpredictable and claustrophobic horror ride that constantly subverts expectations."
  },
  {
    id: "movie-8",
    title: "Old",
    subGenre: "Body Horror / Mystery",
    releaseYear: 2021,
    director: "M. Night Shyamalan",
    cast: ["Gael García Bernal", "Vicky Krieps", "Rufus Sewell", "Alex Wolff"],
    rating: 5.8,
    ratingSource: "IMDb",
    imdbUrl: "https://www.imdb.com/title/tt10954652/",
    posterUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
    review: "A tropical vacation turns into a terrifying race against mortality when a secluded beach causes rapid aging—compressing entire lifetimes into a single day."
  },
  {
    id: "movie-9",
    title: "Evil Dead Rise",
    subGenre: "Supernatural / Body Horror",
    releaseYear: 2023,
    director: "Lee Cronin",
    cast: ["Lily Sullivan", "Alyssa Sutherland", "Morgan Davies"],
    rating: 6.5,
    ratingSource: "IMDb",
    imdbUrl: "https://www.imdb.com/title/tt13345606/",
    review: "A claustrophobic, blood-drenched urban nightmare that breathes vicious new life into the Necronomicon lore with relentless tension."
  },
  {
    id: "movie-10",
    title: "Drag Me to Hell",
    subGenre: "Supernatural / Occult",
    releaseYear: 2009,
    director: "Sam Raimi",
    cast: ["Alison Lohman", "Justin Long", "Lorna Raver"],
    rating: 6.6,
    ratingSource: "IMDb",
    imdbUrl: "https://www.imdb.com/title/tt1127180/",
    review: "A masterclass in energetic dread and dark humor, turning a relentless gypsy curse into an unhinged, high-stakes ride to damnation."
  }
];